name: 'Asciidoctor Convert Action'
description: 'Converts .adoc files to html files. adoc files in the slides folder will be converted using reveal js'
author: 'Quirin Ecker'
branding:
  icon: book
  color: orange
inputs:
  inputPath:
    description: 'path the adoc files are located'
    required: true
  outputPath:
    description: 'path were the html files will be outputed'
    required: true
  slides:
    description: 'if slides are enableed or not'
    required: false
    default: 'true'
runs:
  using: docker
  image: ../../../Dockerfile
  args:
    - ${{ inputs.inputPath }}
    - ${{ inputs.outputPath }}
    - ${{ inputs.slides }}
